### ISSUE TITLE
How to compile JarShrink?

### ISSUE THREAD

**Issue by JoePython1** [Deconimus/JarShrink#2]
How to compile JarShrink?

**Comment by Deconimus** [comment]
In most cases you won't need to compile it yourself since the release binaries will run on any system that the Java Runtime runs on and I intend on keeping these up to date.

If you still want to build it from source I'd suggest you to use an IDE (Eclipse f.i.) or something similar that will do most of the work for you since building executable jars by hand is kind of a painful procedure.

That being said I just gave building it by hand a try myself and the procedure was:

 - Create a tmp directory inside your cloned repository
 - Inside the repository run:
```javac -sourcepath src/ src/jarshrink/Main.java -d tmp/```
 - Inside the tmp directory run:
```jar cf jarShrink.jar *```
 - Edit META-INF/MANIFEST.MF inside the newly created jar so that it reads:
```
Manifest-Version: 1.0
Class-Path: .
Main-Class: jarshrink.Main
```

**Comment by JoePython1** [comment]
What is the link for the release binaries?

**Comment by Deconimus** [comment]
On GitHub release binaries are, if present, commonly found in the release section:
https://github.com/Deconimus/JarShrink/releases
