### ISSUE TITLE
Logging information

### ISSUE THREAD

**Issue by thatsIch** [Deconimus/JarShrink#5]
Hey, after running it I get at first a list which do not have any description:

    ]javax.swing.WindowConstants
    ]javax.swing.JFrame
    ]javax.swing.JRootPane
    ]org.slf4j.Logger
    ]org.slf4j.LoggerFactory
    ]sun.misc.Unsafe

optional dependencies?

**Comment by Deconimus** [comment]
Dependencies listed that way are ones JarShrink has no further information on. These should be classes that aren't included in your JAR either due to being part of the standard Java packages (I'm already discarding the "java." packages from that list) or because they are found somewhere else like in an external JAR file.

**Comment by thatsIch** [comment]
Should be probably stated since the next list has the `dependencies:` description.

**Comment by Deconimus** [comment]
True that, changed in the latest version.
