### ISSUE TITLE
Fails on non-application JARs

### ISSUE THREAD

**Issue by Baughn** [Deconimus/JarShrink#8]
Possibly I'm doing something wrong. But, consider the case of https://madoka.brage.info/baughn/prometheus-integration-0.2.1.jar

This is a plugin for Minecraft servers, not an application. It could, nevertheless, benefit from a good shaking; a glance at it with jdeps shows that it contains a lot of Jetty components that are never used.

However, no matter what I pass for -k, the Dependencies output shows up empty and the resulting .jar contains no class files.

**Comment by Deconimus** [comment]
Sorry for the late response.
I just ran it on the jar you mentioned and it seems to do the job for me.
For instance passing `-k net` retains the `net.*` package and it's dependencies in `kotlin.*`.

**Comment by stechio** [comment]
I experienced the same problem running, for example, on guava-28.0-jre.jar (no class files in shrunk
 jar despite valid `-k` switch specified).

As I discovered, that's because _the undocumented output format for jdeps' `-verbose:class` switch has changed since JDK 9_ (possibly because of the introduction of JPMS module references).

My fix https://github.com/Deconimus/JarShrink/pull/9 solves this issue.
